name: Node.js Package

on:  
  push:
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i -g codecov
      - run: npm i
      - run: npm run flow
      - run: npm run lint
      - run: npm run test
      - run: codecov
 
   
      
      
      
      
